# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3b4006e1b30860c5d11bcbd9ce858d3808956bfa1c84adaab68c44d3d839214cf3d6959feede90659112ba252dc1a21c38a100789f97584d3dff06e6cb7bcce

test:
  secret_key_base: 38b37bdbebb8cd922145690f6cf98e1ec3cf3d8dbd816329056deb56f5bfdf0d26ba147b7785b8f98d98f53c753c3672a86586c0450929404782bbac1b44bd58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
